OrdererOrgs:
  - Name: Orderer
    Domain: chainlinks.com
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer
PeerOrgs:
  - Name: Passportseva
    Domain: passportseva.chainlinks.com
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1
  - Name: Police
    Domain: police.chainlinks.com
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1
  - Name: Airport
    Domain: airport.chainlinks.com
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1