version: '2'

volumes:
  orderer.chainlinks.com:
  peer0.passportseva.chainlinks.com:
  peer1.passportseva.chainlinks.com:
  peer0.police.chainlinks.com:
  peer1.police.chainlinks.com:
  peer0.airport.chainlinks.com:
  peer1.airport.chainlinks.com:


networks:
  chain:

services:

  orderer.chainlinks.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.chainlinks.com
    container_name: orderer.chainlinks.com
    networks:
      - chain

  peer0.passportseva.chainlinks.com:
    container_name: peer0.passportseva.chainlinks.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.passportseva.chainlinks.com
    networks:
      - chain

  peer1.passportseva.chainlinks.com:
    container_name: peer1.passportseva.chainlinks.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.passportseva.chainlinks.com
    networks:
      - chain

  peer0.police.chainlinks.com:
    container_name: peer0.police.chainlinks.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.police.chainlinks.com
    networks:
      - chain

  peer1.police.chainlinks.com:
    container_name: peer1.police.chainlinks.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.police.chainlinks.com
    networks:
      - chain

  peer0.airport.chainlinks.com:
    container_name: peer0.airport.chainlinks.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.airport.chainlinks.com
    networks:
      - chain

  peer1.airport.chainlinks.com:
    container_name: peer1.airport.chainlinks.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.airport.chainlinks.com
    networks:
      - chain

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:$IMAGE_TAG
    tty: true
    stdin_open: true
    environment:
      - SYS_CHANNEL=$SYS_CHANNEL
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      #- FABRIC_LOGGING_SPEC=DEBUG
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.passportseva.chainlinks.com:7051
      - CORE_PEER_LOCALMSPID=PassportsevaMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/passportseva.chainlinks.com/peers/peer0.passportseva.chainlinks.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/passportseva.chainlinks.com/peers/peer0.passportseva.chainlinks.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/passportseva.chainlinks.com/peers/peer0.passportseva.chainlinks.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/passportseva.chainlinks.com/users/Admin@passportseva.chainlinks.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./../chaincode/:/opt/gopath/src/github.com/chaincode
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer.chainlinks.com
      - peer0.passportseva.chainlinks.com
      - peer1.passportseva.chainlinks.com
      - peer0.police.chainlinks.com
      - peer1.police.chainlinks.com
      - peer0.airport.chainlinks.com
      - peer1.airport.chainlinks.com
    networks:
      - chain
