NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca.police.chainlinks.com-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca.police.chainlinks.com-cert.pem
    OrganizationalUnitIdentifier: peer
