# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:

  orderer.chainlinks.com:
    container_name: orderer.chainlinks.com
    extends:
      file: peer-base.yaml
      service: orderer-base
    volumes:
        - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ../crypto-config/ordererOrganizations/chainlinks.com/orderers/orderer.chainlinks.com/msp:/var/hyperledger/orderer/msp
        - ../crypto-config/ordererOrganizations/chainlinks.com/orderers/orderer.chainlinks.com/tls/:/var/hyperledger/orderer/tls
        - orderer.chainlinks.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050

  peer0.passportseva.chainlinks.com:
    container_name: peer0.passportseva.chainlinks.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.passportseva.chainlinks.com
      - CORE_PEER_ADDRESS=peer0.passportseva.chainlinks.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.passportseva.chainlinks.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.passportseva.chainlinks.com:8051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.passportseva.chainlinks.com:7051
      - CORE_PEER_LOCALMSPID=PassportsevaMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/passportseva.chainlinks.com/peers/peer0.passportseva.chainlinks.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/passportseva.chainlinks.com/peers/peer0.passportseva.chainlinks.com/tls:/etc/hyperledger/fabric/tls
        - peer0.passportseva.chainlinks.com:/var/hyperledger/production
    ports:
      - 7051:7051

  peer1.passportseva.chainlinks.com:
    container_name: peer1.passportseva.chainlinks.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.passportseva.chainlinks.com
      - CORE_PEER_ADDRESS=peer1.passportseva.chainlinks.com:8051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
      - CORE_PEER_CHAINCODEADDRESS=peer1.org1.passportseva.chainlinks.com:8052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org1.passportseva.chainlinks.com:8051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.passportseva.chainlinks.com:7051
      - CORE_PEER_LOCALMSPID=PassportsevaMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/passportseva.chainlinks.com/peers/peer1.passportseva.chainlinks.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/passportseva.chainlinks.com/peers/peer1.passportseva.chainlinks.com/tls:/etc/hyperledger/fabric/tls
        - peer1.passportseva.chainlinks.com:/var/hyperledger/production
    ports:
      - 8051:8051

  peer0.police.chainlinks.com:
    container_name: peer0.police.chainlinks.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.police.chainlinks.com
      - CORE_PEER_ADDRESS=peer0.police.chainlinks.com:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=peer0.police.chainlinks.com:9052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.police.chainlinks.com:9051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.police.chainlinks.com:10051
      - CORE_PEER_LOCALMSPID=PoliceMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/police.chainlinks.com/peers/peer0.police.chainlinks.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/police.chainlinks.com/peers/peer0.police.chainlinks.com/tls:/etc/hyperledger/fabric/tls
        - peer0.police.chainlinks.com:/var/hyperledger/production
    ports:
      - 9051:9051

  peer1.police.chainlinks.com:
    container_name: peer1.police.chainlinks.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.police.chainlinks.com
      - CORE_PEER_ADDRESS=peer1.police.chainlinks.com:10051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:10051
      - CORE_PEER_CHAINCODEADDRESS=peer1.police.chainlinks.com:10052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:10052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.police.chainlinks.com:10051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.police.chainlinks.com:9051
      - CORE_PEER_LOCALMSPID=PoliceMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/police.chainlinks.com/peers/peer1.police.chainlinks.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/police.chainlinks.com/peers/peer1.police.chainlinks.com/tls:/etc/hyperledger/fabric/tls
        - peer1.police.chainlinks.com:/var/hyperledger/production
    ports:
      - 10051:10051

  peer0.airport.chainlinks.com:
    container_name: peer0.airport.chainlinks.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.airport.chainlinks.com
      - CORE_PEER_ADDRESS=peer0.airport.chainlinks.com:11051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:11051
      - CORE_PEER_CHAINCODEADDRESS=peer0.airport.chainlinks.com:11052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:11052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.airport.chainlinks.com:12051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.airport.chainlinks.com:11051
      - CORE_PEER_LOCALMSPID=AirportMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/airport.chainlinks.com/peers/peer0.airport.chainlinks.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/airport.chainlinks.com/peers/peer0.airport.chainlinks.com/tls:/etc/hyperledger/fabric/tls
        - peer0.airport.chainlinks.com:/var/hyperledger/production
    ports:
      - 11051:11051

  peer1.airport.chainlinks.com:
    container_name: peer1.airport.chainlinks.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.airport.chainlinks.com
      - CORE_PEER_ADDRESS=peer1.airport.chainlinks.com:12051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:12051
      - CORE_PEER_CHAINCODEADDRESS=peer1.airport.chainlinks.com:12052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:12052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.airport.chainlinks.com:12051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.airport.chainlinks.com:11051
      - CORE_PEER_LOCALMSPID=AirportMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/airport.chainlinks.com/peers/peer1.airport.chainlinks.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/airport.chainlinks.com/peers/peer1.airport.chainlinks.com/tls:/etc/hyperledger/fabric/tls
        - peer1.airport.chainlinks.com:/var/hyperledger/production
    ports:
      - 12051:12051
